package db.conn;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mohit
 */
public class Forgot extends javax.swing.JFrame {

    private String user;

    /**
     * Creates new form Forgot
     */
    public Forgot() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        newpass4 = new javax.swing.JLabel();
        confpassword4 = new javax.swing.JLabel();
        newpassword4 = new javax.swing.JPasswordField();
        confirmpassword4 = new javax.swing.JPasswordField();
        cancel4 = new javax.swing.JButton();
        resetpass4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        forgotpasspanel = new javax.swing.JPanel();
        fpasswordheading = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        sercurity = new javax.swing.JLabel();
        anssecurity = new javax.swing.JLabel();
        securityoption = new javax.swing.JComboBox<>();
        usernametext = new javax.swing.JTextField();
        answersecurity = new javax.swing.JTextField();
        returnlogin = new javax.swing.JLabel();
        newuser = new javax.swing.JLabel();
        tip = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        headingpanel3 = new javax.swing.JPanel();

        jFrame2.setLocationRelativeTo(null);
        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame2.setMaximizedBounds(new java.awt.Rectangle(800, 300, 800, 300));
        jFrame2.setMinimumSize(new java.awt.Dimension(800, 300));
        jFrame2.setResizable(false);
        jFrame2.setSize(new java.awt.Dimension(800, 300));
        jFrame2.setType(java.awt.Window.Type.POPUP);

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setPreferredSize(new java.awt.Dimension(830, 332));

        newpass4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newpass4.setForeground(new java.awt.Color(255, 255, 255));
        newpass4.setText("New Password:");

        confpassword4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confpassword4.setForeground(new java.awt.Color(255, 255, 255));
        confpassword4.setText("Confirm Password:");

        newpassword4.setBackground(new java.awt.Color(108, 122, 137));
        newpassword4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newpassword4.setToolTipText("");
        newpassword4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassword4newpassword1ActionPerformed(evt);
            }
        });

        confirmpassword4.setBackground(new java.awt.Color(108, 122, 137));
        confirmpassword4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmpassword4.setToolTipText("Re-enter password");

        cancel4.setBackground(new java.awt.Color(255, 0, 0));
        cancel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cancel4.setContentAreaFilled(false);
        cancel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel4.setFocusCycleRoot(true);
        cancel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancel4.setLabel("Cancel");
        cancel4.setOpaque(true);
        cancel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel4cancel1ActionPerformed(evt);
            }
        });

        resetpass4.setBackground(new java.awt.Color(0, 204, 0));
        resetpass4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetpass4.setText("Reset Password");
        resetpass4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        resetpass4.setContentAreaFilled(false);
        resetpass4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetpass4.setOpaque(true);
        resetpass4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetpass4resetpass1MousePressed(evt);
            }
        });
        resetpass4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetpass4resetpass1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("*Enter new password");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newpass4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confpassword4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cancel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(resetpass4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(confirmpassword4)
                            .addComponent(newpassword4))))
                .addGap(145, 205, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpass4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newpassword4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confpassword4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmpassword4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetpass4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
            .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        forgotpasspanel.setBackground(new java.awt.Color(44, 62, 80));
        forgotpasspanel.setFocusCycleRoot(true);
        forgotpasspanel.setFocusTraversalPolicyProvider(true);

        fpasswordheading.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        fpasswordheading.setForeground(new java.awt.Color(255, 255, 255));
        fpasswordheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fpasswordheading.setText(" FORGOT PASSWORD");

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username:");

        sercurity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sercurity.setForeground(new java.awt.Color(255, 255, 255));
        sercurity.setText("Security Question:");

        anssecurity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        anssecurity.setForeground(new java.awt.Color(255, 255, 255));
        anssecurity.setText("Answer:");

        securityoption.setBackground(new java.awt.Color(108, 122, 137));
        securityoption.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        securityoption.setMaximumRowCount(20);
        securityoption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your childhood nickname?", "Who is your favourite actor?", "What is your school name?", "Who is your favourite actress?", "Which is your favourite animal?", "What is your pet name?", "What is name of your favourite movie?", "What is your college name?", "What is your crush name?", "" }));
        securityoption.setToolTipText("Enter a security question which you should remember if you forgot your password or username");
        securityoption.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        securityoption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        securityoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityoptionActionPerformed(evt);
            }
        });

        usernametext.setBackground(new java.awt.Color(108, 122, 137));
        usernametext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernametext.setToolTipText("Enter Mobile Number or Email id");
        usernametext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametextActionPerformed(evt);
            }
        });

        answersecurity.setBackground(new java.awt.Color(108, 122, 137));
        answersecurity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answersecurity.setToolTipText("Enter answer of the security question you choosed");
        answersecurity.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        answersecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answersecurityActionPerformed(evt);
            }
        });

        returnlogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        returnlogin.setForeground(new java.awt.Color(255, 255, 0));
        returnlogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnlogin.setText("Return to login?");
        returnlogin.setToolTipText("Login ");
        returnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnloginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                returnloginMousePressed(evt);
            }
        });

        newuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newuser.setForeground(new java.awt.Color(255, 255, 0));
        newuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newuser.setText("Create New User");
        newuser.setToolTipText("Signup");
        newuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserMouseClicked(evt);
            }
        });

        tip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tip.setForeground(new java.awt.Color(255, 255, 0));
        tip.setText("**Please enter your username and security question");

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Validate");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forgotpasspanelLayout = new javax.swing.GroupLayout(forgotpasspanel);
        forgotpasspanel.setLayout(forgotpasspanelLayout);
        forgotpasspanelLayout.setHorizontalGroup(
            forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sercurity, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anssecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgotpasspanelLayout.createSequentialGroup()
                                            .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(securityoption, 0, 370, Short.MAX_VALUE)
                                                .addComponent(answersecurity))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE))
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                                        .addComponent(returnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(newuser, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(405, 405, 405))))
                            .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                        .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(fpasswordheading, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        forgotpasspanelLayout.setVerticalGroup(
            forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(fpasswordheading, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(tip)
                .addGap(15, 15, 15)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sercurity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityoption, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anssecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answersecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newuser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        headingpanel3.setBackground(new java.awt.Color(248, 148, 6));
        headingpanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout headingpanel3Layout = new javax.swing.GroupLayout(headingpanel3);
        headingpanel3.setLayout(headingpanel3Layout);
        headingpanel3Layout.setHorizontalGroup(
            headingpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headingpanel3Layout.setVerticalGroup(
            headingpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(forgotpasspanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgotpasspanel, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void securityoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityoptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityoptionActionPerformed

    private void usernametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametextActionPerformed

    private void answersecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answersecurityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answersecurityActionPerformed

    private void returnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnloginMouseClicked
        this.dispose();
        new LoginFinal().setVisible(true);
    }//GEN-LAST:event_returnloginMouseClicked

    private void returnloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnloginMousePressed
        this.dispose();
        new LoginFinal().setVisible(true);
    }//GEN-LAST:event_returnloginMousePressed

    private void newuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserMouseClicked
        this.dispose();
        new SignUp().setVisible(true);
    }//GEN-LAST:event_newuserMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("Connection Successful");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/itsa?useTimezone=true&serverTimezone=UTC", "root","");
            // JOptionPane.showConfirmDialog(null, "Connection Successful");
            //String name = "mohitjadhav";
            Statement stmnt= con.createStatement();
            String query = ("SELECT * FROM `users` where `username`=? and `answersecurityquestion`=? ");
            PreparedStatement ps = con.prepareStatement(query);
            user = usernametext.getText();
            ps.setString(1,user);
            ps.setString(2,answersecurity.getText());
            
            ResultSet executeQuery = ps.executeQuery();
            if(executeQuery.next()){
                jFrame2.setVisible(true);
                jFrame2.setLocationRelativeTo(null);
            }
            else{
                JOptionPane.showMessageDialog(null,"Check Credentials...");
                usernametext.setText("");
                answersecurity.setText("");
            }
        }
        catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null,"Please Contact Support Team");
        } catch (SQLException ex) {
            //  System.out.println();
            JOptionPane.showMessageDialog(null,"Please Contact Support Team");

        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newpassword4newpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassword4newpassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassword4newpassword1ActionPerformed

    private void cancel4cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel4cancel1ActionPerformed
            jFrame2.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancel4cancel1ActionPerformed

    private void resetpass4resetpass1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetpass4resetpass1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetpass4resetpass1MousePressed

     public  String rev(char  a[] ,int d){
       String pass = null;
        for(int i=0;i<d;i++){
         pass = pass + a[i];   
        }
        String retstr = pass.substring(4);
        return retstr;
    }
    private void resetpass4resetpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetpass4resetpass1ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            // System.out.println("Connection Successful");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/itsa?useTimezone=true&serverTimezone=UTC", "root","");
            
            
            Statement stmnt= con.createStatement();
            if(String.valueOf(newpassword4.getPassword()).equals(String.valueOf(confirmpassword4.getPassword()))){
                if(!((String.valueOf(newpassword4.getPassword()).isEmpty()) && (String.valueOf(confirmpassword4.getPassword()).isEmpty()))){
                    
                    char [] ch = newpassword4.getPassword();
                    String pass = rev(ch,4);
            
                    
                    String query = "UPDATE `users` SET `userpassword`= ? WHERE username = ?";
                    PreparedStatement ps = con.prepareStatement(query);
                    ps.setString(1,pass);
                    ps.setString(2,user);
                    int executeUpdate = ps.executeUpdate();
                    if(executeUpdate>0)
                    {
                        JOptionPane.showMessageDialog(null, "Password Changed Successfully!");
                        new LoginFinal().setVisible(true);
                        this.dispose();
                        jFrame2.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Please try again");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please enter new password");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Password should match confirm password", "Password Error", ERROR_MESSAGE);
                newpassword4.setText("");
                confirmpassword4.setText("");
            }

        }
        catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null,"Please Contact Support Team");
        } catch (SQLException ex) {
            //  System.out.println();
            JOptionPane.showMessageDialog(null,ex.getMessage());

        }      
    }//GEN-LAST:event_resetpass4resetpass1ActionPerformed
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anssecurity;
    private javax.swing.JTextField answersecurity;
    private javax.swing.JButton cancel4;
    private javax.swing.JPasswordField confirmpassword4;
    private javax.swing.JLabel confpassword4;
    private javax.swing.JPanel forgotpasspanel;
    private javax.swing.JLabel fpasswordheading;
    private javax.swing.JPanel headingpanel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel newpass4;
    private javax.swing.JPasswordField newpassword4;
    private javax.swing.JLabel newuser;
    private javax.swing.JButton resetpass4;
    private javax.swing.JLabel returnlogin;
    private javax.swing.JComboBox<String> securityoption;
    private javax.swing.JLabel sercurity;
    private javax.swing.JLabel tip;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernametext;
    // End of variables declaration//GEN-END:variables
}
