package db.conn;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mohit
 */
public class ForgotFinal extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotFinal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        forgotpasspanel = new javax.swing.JPanel();
        fpasswordheading = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        sercurity = new javax.swing.JLabel();
        anssecurity = new javax.swing.JLabel();
        securityoption = new javax.swing.JComboBox<>();
        usernametext = new javax.swing.JTextField();
        answersecurity = new javax.swing.JTextField();
        newpass = new javax.swing.JLabel();
        confpassword = new javax.swing.JLabel();
        resetpass = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        validate = new javax.swing.JButton();
        returnlogin = new javax.swing.JLabel();
        newuser = new javax.swing.JLabel();
        tip = new javax.swing.JLabel();
        newpassword = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        headingpanel = new javax.swing.JPanel();
        pccoeicon = new javax.swing.JLabel();
        pccoename = new javax.swing.JLabel();
        itsaname = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        supportuslabel = new javax.swing.JLabel();
        instagramlogo = new javax.swing.JLabel();
        facebooklogo = new javax.swing.JLabel();
        youtubelogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jDialog1.getAccessibleContext().setAccessibleParent(resetpass);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 600, 800));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setIconImages(null);
        setMaximizedBounds(new java.awt.Rectangle(100, 100, 800, 800));
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setName("forgotpasswordframe"); // NOI18N
        setResizable(false);

        forgotpasspanel.setBackground(new java.awt.Color(44, 62, 80));
        forgotpasspanel.setFocusCycleRoot(true);
        forgotpasspanel.setFocusTraversalPolicyProvider(true);

        fpasswordheading.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        fpasswordheading.setForeground(new java.awt.Color(255, 255, 255));
        fpasswordheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fpasswordheading.setText("Forgot password?");

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username:");

        sercurity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sercurity.setForeground(new java.awt.Color(255, 255, 255));
        sercurity.setText("Security Question:");

        anssecurity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        anssecurity.setForeground(new java.awt.Color(255, 255, 255));
        anssecurity.setText("Answer:");

        securityoption.setBackground(new java.awt.Color(108, 122, 137));
        securityoption.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        securityoption.setMaximumRowCount(20);
        securityoption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your childhood nickname?", "Who is your favourite actor?", "What is your school name?", "Who is your favourite actress?", "Which is your favourite animal?", "What is your pet name?", "What is name of your favourite movie?", "What is your college name?", "What is your crush name?", "" }));
        securityoption.setToolTipText("Enter a security question which you should remember if you forgot your password or username");
        securityoption.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        securityoption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        securityoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityoptionActionPerformed(evt);
            }
        });

        usernametext.setBackground(new java.awt.Color(108, 122, 137));
        usernametext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernametext.setToolTipText("Enter Mobile Number or Email id");
        usernametext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernametext.setNextFocusableComponent(securityoption);

        answersecurity.setBackground(new java.awt.Color(108, 122, 137));
        answersecurity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answersecurity.setToolTipText("Enter answer of the security question you choosed");
        answersecurity.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        answersecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answersecurityActionPerformed(evt);
            }
        });

        newpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newpass.setForeground(new java.awt.Color(255, 255, 255));
        newpass.setText("New Password:");

        confpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confpassword.setForeground(new java.awt.Color(255, 255, 255));
        confpassword.setText("Confirm Password:");

        resetpass.setBackground(new java.awt.Color(0, 204, 0));
        resetpass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetpass.setForeground(new java.awt.Color(255, 255, 255));
        resetpass.setText("Reset Password");
        resetpass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.black));
        resetpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetpassMousePressed(evt);
            }
        });
        resetpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetpassActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(255, 0, 0));
        cancel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.black));
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setFocusCycleRoot(true);
        cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancel.setLabel("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        validate.setBackground(new java.awt.Color(0, 204, 0));
        validate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        validate.setForeground(new java.awt.Color(255, 255, 255));
        validate.setText("Validate");
        validate.setToolTipText("Get your account validated to change password");
        validate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.black));
        validate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        validate.setMaximumSize(new java.awt.Dimension(103, 27));
        validate.setMinimumSize(new java.awt.Dimension(103, 27));
        validate.setPreferredSize(new java.awt.Dimension(103, 27));
        validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateActionPerformed(evt);
            }
        });

        returnlogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        returnlogin.setForeground(new java.awt.Color(255, 255, 0));
        returnlogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnlogin.setText("Return to login?");
        returnlogin.setToolTipText("Login ");
        returnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnloginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                returnloginMousePressed(evt);
            }
        });

        newuser.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        newuser.setForeground(new java.awt.Color(255, 255, 0));
        newuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newuser.setText("Create New User");
        newuser.setToolTipText("Signup");
        newuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserMouseClicked(evt);
            }
        });

        tip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tip.setForeground(new java.awt.Color(255, 255, 0));
        tip.setText("**Please enter your username and security question");

        newpassword.setBackground(new java.awt.Color(108, 122, 137));
        newpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newpassword.setToolTipText("Should atleast contain a symbol & a digit");
        newpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpasswordActionPerformed(evt);
            }
        });

        confirmpassword.setBackground(new java.awt.Color(108, 122, 137));
        confirmpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmpassword.setToolTipText("Re-enter password");

        javax.swing.GroupLayout forgotpasspanelLayout = new javax.swing.GroupLayout(forgotpasspanel);
        forgotpasspanel.setLayout(forgotpasspanelLayout);
        forgotpasspanelLayout.setHorizontalGroup(
            forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sercurity, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anssecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confpassword))
                                .addGap(30, 30, 30)
                                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgotpasspanelLayout.createSequentialGroup()
                                        .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(41, 41, 41)
                                        .addComponent(resetpass, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                                        .addGap(183, 183, 183)
                                        .addComponent(newuser, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgotpasspanelLayout.createSequentialGroup()
                                        .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(confirmpassword, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(newpassword, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(validate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(securityoption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(answersecurity))
                                        .addGap(4, 4, 4))))))
                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(fpasswordheading, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(returnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        forgotpasspanelLayout.setVerticalGroup(
            forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(fpasswordheading, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(tip)
                .addGap(15, 15, 15)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sercurity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityoption, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anssecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answersecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(validate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpass)
                    .addComponent(newpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confpassword))
                .addGap(29, 29, 29)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resetpass, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newuser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        headingpanel.setBackground(new java.awt.Color(248, 148, 6));
        headingpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        pccoeicon.setBackground(new java.awt.Color(0, 0, 0));

        pccoename.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pccoename.setForeground(new java.awt.Color(255, 255, 255));
        pccoename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pccoename.setText("");

        itsaname.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        itsaname.setForeground(new java.awt.Color(255, 255, 255));
        itsaname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itsaname.setText("");

        javax.swing.GroupLayout headingpanelLayout = new javax.swing.GroupLayout(headingpanel);
        headingpanel.setLayout(headingpanelLayout);
        headingpanelLayout.setHorizontalGroup(
            headingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingpanelLayout.createSequentialGroup()
                .addComponent(pccoeicon, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(headingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pccoename, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itsaname, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        headingpanelLayout.setVerticalGroup(
            headingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pccoeicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headingpanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(pccoename, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itsaname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        footer.setBackground(new java.awt.Color(248, 148, 6));
        footer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        supportuslabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        supportuslabel.setText("Support Us:");

        
        instagramlogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        facebooklogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        youtubelogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(supportuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(instagramlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facebooklogo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(youtubelogo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addComponent(supportuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(youtubelogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(facebooklogo, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(instagramlogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

    

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headingpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(forgotpasspanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headingpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(forgotpasspanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetpassActionPerformed
        JOptionPane.showConfirmDialog(rootPane,"Password Changed for "+ usernametext.getText()+ " return to login and try login");
    }//GEN-LAST:event_resetpassActionPerformed

    private void answersecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answersecurityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answersecurityActionPerformed

    private void validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validateActionPerformed

    private void newpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswordActionPerformed

    private void newuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserMouseClicked
        this.dispose();
        new SignUp().setVisible(true);  
    }//GEN-LAST:event_newuserMouseClicked

    private void returnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnloginMouseClicked
            new LoginFinal().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_returnloginMouseClicked

    private void securityoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityoptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityoptionActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void returnloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnloginMousePressed
            new LoginFinal().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_returnloginMousePressed

    private void resetpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetpassMousePressed
            
    }//GEN-LAST:event_resetpassMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anssecurity;
    private javax.swing.JTextField answersecurity;
    private javax.swing.JButton cancel;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JLabel confpassword;
    private javax.swing.JLabel facebooklogo;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel forgotpasspanel;
    private javax.swing.JLabel fpasswordheading;
    private javax.swing.JPanel headingpanel;
    private javax.swing.JLabel instagramlogo;
    private javax.swing.JLabel itsaname;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newpass;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JLabel newuser;
    private javax.swing.JLabel pccoeicon;
    private javax.swing.JLabel pccoename;
    private javax.swing.JButton resetpass;
    private javax.swing.JLabel returnlogin;
    private javax.swing.JComboBox<String> securityoption;
    private javax.swing.JLabel sercurity;
    private javax.swing.JLabel supportuslabel;
    private javax.swing.JLabel tip;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernametext;
    private javax.swing.JButton validate;
    private javax.swing.JLabel youtubelogo;
    // End of variables declaration//GEN-END:variables
}
